spring:
  app:
    name: ${APP_NAME}

  profiles:
      active: prod

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  servlet:
    multipart:
      max-file-size: 2MB     # Maximum size of a single uploaded file
      max-request-size: 10MB # Maximum size of a complete request (all files + form data)

jwt:
  secret: ${JWT_SECRET}

cloudinary:
  name: ${CLOUDINARY_NAME}
  api:
    key: ${CLOUDINARY_KEY}
    secret: ${CLOUDINARY_SECRET}