# A DataSource is a factory for connections to the physical databases. It uses a URL, username, and password to establish the database connection.
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/furida
    username: root
    password: admin

# Hibernate ddl-auto automatically validates or exports schema DDL to the database when the SessionFactory is created.
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: d829cdbf49f27fd8db229bc3d8304663d271bab133c86b6166311bba63310a40

cloudinary:
  name: amankr8
  api:
    key: 177184845799143
    secret: q6rVgGB6PZJ8RbKOxE37KKsOe2Y