# A DataSource is a factory for connections to the physical databases. It uses a URL, username, and password to establish the database connection.
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # Hibernate ddl-auto automatically validates or exports schema DDL to the database when the SessionFactory is created.
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update