spring:
  profiles:
    active: prod
      
  spring:
    servlet:
      multipart:
        max-file-size: 2MB     # Maximum size of a single uploaded file
        max-request-size: 10MB # Maximum size of a complete request (all files + form data)

jwt:
  secret: ${JWT_SECRET}

cloudinary:
  name: ${CLOUDINARY_NAME}
  api:
    key: ${CLOUDINARY_KEY}
    secret: ${CLOUDINARY_SECRET}