CREATE TABLE app_user (
    u_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    u_email VARCHAR(255) UNIQUE,
    u_password VARCHAR(255),
    u_role VARCHAR(255) CHECK (u_role IN ('EDITOR','ADMIN')),
    u_username VARCHAR(255) UNIQUE,
    PRIMARY KEY (u_id)
);

CREATE TABLE document (
    d_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    pj_id INTEGER,
    d_desc VARCHAR(255),
    d_name VARCHAR(255),
    PRIMARY KEY (d_id)
);

CREATE TABLE document_file (
    d_id INTEGER UNIQUE,
    df_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    df_public_id VARCHAR(255),
    df_url VARCHAR(255),
    PRIMARY KEY (df_id)
);

CREATE TABLE message (
    m_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    m_read BOOLEAN,
    m_date TIMESTAMP(6),
    m_msg VARCHAR(510),
    m_email VARCHAR(255),
    m_name VARCHAR(255),
    PRIMARY KEY (m_id)
);

CREATE TABLE post (
    p_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    p_date TIMESTAMP(6),
    p_content VARCHAR(510),
    p_title VARCHAR(255),
    PRIMARY KEY (p_id)
);

CREATE TABLE post_image (
    p_id INTEGER,
    pi_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    pi_public_id VARCHAR(255),
    pi_url VARCHAR(255),
    PRIMARY KEY (pi_id)
);

CREATE TABLE project (
    pj_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    pj_desc VARCHAR(255),
    pj_name VARCHAR(255),
    pj_date TIMESTAMP(6),
    PRIMARY KEY (pj_id)
);

ALTER TABLE IF EXISTS document
   ADD CONSTRAINT FKnh7swk2hmn90femy91f1l4h3f
   FOREIGN KEY (pj_id)
   REFERENCES project;

ALTER TABLE IF EXISTS document_file
  ADD CONSTRAINT FKkqtvox1kaea1uy2r4x6a9qaa6
  FOREIGN KEY (d_id)
  REFERENCES document;

ALTER TABLE IF EXISTS post_image
   ADD CONSTRAINT FK8ism9svyd7x9jrtjuoxoanhyy
   FOREIGN KEY (p_id)
   REFERENCES post;