create table app_user (
    u_id integer generated by default as identity,
    u_email varchar(255) unique,
    u_password varchar(255),
    u_role varchar(255) check (u_role in ('EDITOR','ADMIN')),
    u_username varchar(255) unique,
    primary key (u_id)
);

create table document (
    d_id integer generated by default as identity,
    pj_id integer,
    d_desc varchar(255),
    d_name varchar(255),
    primary key (d_id)
);

create table document_file (
    d_id integer unique,
    df_id integer generated by default as identity,
    df_public_id varchar(255),
    df_url varchar(255),
    primary key (df_id)
);

create table message (
    m_id integer generated by default as identity,
    m_read boolean,
    m_date timestamp(6),
    m_msg varchar(510),
    m_email varchar(255),
    m_name varchar(255),
    primary key (m_id)
);

create table post (
    p_id integer generated by default as identity,
    p_date timestamp(6),
    p_content varchar(510),
    p_title varchar(255),
    primary key (p_id)
);

create table post_image (
    p_id integer,
    pi_id integer generated by default as identity,
    pi_public_id varchar(255),
    pi_url varchar(255),
    primary key (pi_id)
);

create table project (
    pj_id integer generated by default as identity,
    pj_desc varchar(255),
    pj_name varchar(255),
    pj_date timestamp(6),
    primary key (pj_id)
);

alter table if exists document
   add constraint FKnh7swk2hmn90femy91f1l4h3f
   foreign key (pj_id)
   references project;

alter table if exists document_file
  add constraint FKkqtvox1kaea1uy2r4x6a9qaa6
  foreign key (d_id)
  references document;

alter table if exists post_image
   add constraint FK8ism9svyd7x9jrtjuoxoanhyy
   foreign key (p_id)
   references post;