CREATE TABLE app_user (
    u_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    u_username VARCHAR(255) UNIQUE,
    u_email VARCHAR(255) UNIQUE,
    u_password VARCHAR(255),
    u_role VARCHAR(255) CHECK (u_role IN ('EDITOR', 'ADMIN')),
    PRIMARY KEY (u_id)
);