-- Create the app_user table if it does not exist
CREATE TABLE IF NOT EXISTS app_user (
    u_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    u_email VARCHAR(255) UNIQUE,
    u_password VARCHAR(255),
    u_role VARCHAR(255) CHECK (u_role IN ('EDITOR','ADMIN')),
    u_username VARCHAR(255) UNIQUE,
    PRIMARY KEY (u_id)
)