CREATE TABLE app_user (
    u_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    u_username VARCHAR(255) UNIQUE,
    u_email VARCHAR(255) UNIQUE,
    u_password VARCHAR(255),
    u_role VARCHAR(255) CHECK (u_role IN ('EDITOR', 'ADMIN')),
    PRIMARY KEY (u_id)
);

CREATE TABLE project (
    pj_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    pj_name VARCHAR(255),
    pj_desc VARCHAR(255),
    pj_address VARCHAR(255),
    PRIMARY KEY (pj_id)
);

CREATE TABLE document (
    d_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    d_name VARCHAR(255),
    d_desc VARCHAR(255),
    pj_id INTEGER,
    PRIMARY KEY (d_id),
    FOREIGN KEY (pj_id) REFERENCES project(pj_id)
);

CREATE TABLE document_file (
    df_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    df_public_id VARCHAR(255),
    df_url VARCHAR(255),
    d_id INTEGER,
    PRIMARY KEY (df_id),
    FOREIGN KEY (d_id) REFERENCES document(d_id)
);

CREATE TABLE post (
    p_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    p_title VARCHAR(255),
    p_content VARCHAR(510),
    p_date TIMESTAMP,
    PRIMARY KEY (p_id)
);

CREATE TABLE post_image (
    pi_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    pi_public_id VARCHAR(255),
    pi_url VARCHAR(255),
    p_id INTEGER,
    PRIMARY KEY (pi_id),
    FOREIGN KEY (p_id) REFERENCES post(p_id)
);

CREATE TABLE message (
    m_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    m_name VARCHAR(255),
    m_email VARCHAR(255),
    m_msg VARCHAR(510),
    m_date TIMESTAMP,
    m_read BOOLEAN,
    PRIMARY KEY (m_id)
);