CREATE TABLE document (
    d_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    d_name VARCHAR(255),
    d_desc VARCHAR(255),
    pj_id INTEGER,
    PRIMARY KEY (d_id),
    FOREIGN KEY (pj_id) REFERENCES project(pj_id)
);