CREATE TABLE document_file (
    df_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    df_public_id VARCHAR(255),
    df_url VARCHAR(255),
    d_id INTEGER,
    PRIMARY KEY (df_id),
    FOREIGN KEY (d_id) REFERENCES document(d_id)
);